DROP TABLE WORKED_HOURS CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP VIEW JOIN_VIEW;

CREATE TABLE EMPLOYEE (ID NUMBER(3) NOT NULL , FIRST_NAME VARCHAR2(30) NOT NULL, LAST_NAME VARCHAR2(30) NOT NULL, PRIMARY KEY(ID));
/
CREATE TABLE WORKED_HOURS(EMPLOYEE_ID NUMBER(3), HOURS NUMBER(3),  FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE (ID));
/
CREATE VIEW JOIN_VIEW AS SELECT * FROM EMPLOYEE e JOIN  WORKED_HOURS  w  ON
e.ID=w.EMPLOYEE_ID;
/
CREATE OR REPLACE TRIGGER JOIN_VIEW_INSERT_TRIGGER INSTEAD OF INSERT ON JOIN_VIEW
BEGIN
    INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES(:NEW.ID,:NEW.FIRST_NAME,:NEW.LAST_NAME);
    INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(:NEW.EMPLOYEE_ID,:NEW.HOURS);
END;
/
CREATE OR REPLACE TRIGGER JOIN_VIEW_DELETE_TRIGGER INSTEAD OF DELETE ON JOIN_VIEW
BEGIN
    DELETE FROM WORKED_HOURS WHERE EMPLOYEE_ID=:OLD.EMPLOYEE_ID;
    DELETE FROM EMPLOYEE WHERE ID=:OLD.ID;
END;
/
CREATE OR REPLACE TRIGGER JOIN_VIEW_UPDATE_TRIGGER INSTEAD OF UPDATE ON JOIN_VIEW
BEGIN 
    UPDATE EMPLOYEE SET ID=:NEW.ID, FIRST_NAME=:NEW.FIRST_NAME, LAST_NAME=:NEW.LAST_NAME WHERE ID=:OLD.ID;
    UPDATE WORKED_HOURS SET EMPLOYEE_ID = :NEW.EMPLOYEE_ID, HOURS=:NEW.HOURS WHERE EMPLOYEE_ID=:OLD.EMPLOYEE_ID;
END;
/

INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (100, 'Ionut', 'Popescu');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (101, 'Filip', 'Later');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (102, 'Vlad', 'Zoltan');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (103, 'Sorina', 'Maricari');
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME) VALUES (104, 'Iuliana', 'Boca');

INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(100, 165);
INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(101, 165);
INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(102, 160);
INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(103, 150);
INSERT INTO WORKED_HOURS(EMPLOYEE_ID,HOURS) VALUES(104, 162);

-- EXAMPLE OF OPERATIONS ON THE JOIN_VIEW USING:

INSERT INTO JOIN_VIEW (ID, FIRST_NAME, LAST_NAME, EMPLOYEE_ID, HOURS) VALUES (106, 'NEW_FIRST_NAME', 'NEW_LAST_NAME',106,170);
DELETE FROM JOIN_VIEW WHERE ID=106;
UPDATE JOIN_VIEW SET LAST_NAME='REPLACEMENT', HOURS=170 WHERE ID=104;