DROP TABLE LOGTYPE_TABLE CASCADE CONSTRAINTS;
CREATE TABLE  LOGTYPE_TABLE (MODIFIED_BY VARCHAR2(60), MODIFIED_AT TIMESTAMP, INCREASED_GRADES NUMBER);
/

DROP TRIGGER INCREASE_GRADE;
CREATE  TRIGGER INCREASE_GRADE
FOR UPDATE ON NOTE COMPOUND TRIGGER

v_increasedGradesCounter NUMBER:=0;
v_userName VARCHAR2(60);
v_timeStamp DATE;

BEFORE EACH ROW IS
BEGIN

    IF :OLD.valoare>:NEW.valoare THEN 
        :NEW.valoare:=:OLD.valoare;
    ELSE
        v_increasedGradesCounter:=v_increasedGradesCounter+1;
    END IF;  
END BEFORE EACH ROW;

AFTER STATEMENT IS
BEGIN 
    v_userName:=ora_login_user;

    INSERT INTO LOGTYPE_TABLE (MODIFIED_BY,MODIFIED_AT,INCREASED_GRADES) VALUES (v_userName, CURRENT_TIMESTAMP, v_increasedGradesCounter);

END AFTER STATEMENT;

END;
/

UPDATE NOTE SET valoare=10 WHERE ID_STUDENT=1023 AND ID_CURS IN (16,17);