set serveroutput on;
DECLARE
V_DATA_NASTERE CONSTANT VARCHAR(30):= '01-01-2000';
V_MONTHS INT ;
V_DAY VARCHAR(30);
V_NUMBER_DAYS INT;
V_BIRTH_DATE DATE;

BEGIN 

SELECT TRUNC(MONTHS_BETWEEN (SYSDATE, TO_DATE(V_DATA_NASTERE ,'DD-MM-YYYY'))) INTO V_MONTHS
    FROM DUAL;
    
V_DAY := TO_CHAR(TO_DATE(V_DATA_NASTERE, 'DD-MM-YYYY'),'DAY');

SELECT ADD_MONTHS(TO_DATE(V_DATA_NASTERE ,'DD-MM-YYYY'), V_MONTHS) INTO V_BIRTH_DATE
FROM DUAL;

SELECT (SYSDATE - V_BIRTH_DATE ) INTO V_NUMBER_DAYS
FROM DUAL;
    
    
 DBMS_OUTPUT.put_line('LUNILE DE PE 27.07.1997: '|| V_MONTHS);
 DBMS_OUTPUT.put_line('NUMARUL DE ZILE: '|| V_NUMBER_DAYS);
 DBMS_OUTPUT.put_line('ZIUA IN CARE S-A NASCUT: '||  V_DAY);

END;